spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

# AWS S3 Configuration (Development)
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION}
    prefix: ${AWS_S3_PREFIX}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}

# User Configuration
user:
  default-profile-image-url: ${USER_DEFAULT_PROFILE_IMAGE_URL}

# Shop Configuration
shop:
  default-image-url: ${SHOP_DEFAULT_IMAGE_URL}
