spring:
  application:
    name: gotcha-server
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

kakao:
  api:
    rest-api-key: ${KAKAO_REST_API_KEY}
    base-url: https://dapi.kakao.com

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha